-- Insert some users
INSERT INTO USERS (USERNAME, PASSWORD, FIRST_NAME, SURNAME, PHONE_NUMBER)
VALUES ('user1', 'password1', 'John', 'Doe', '123-456-7890');

INSERT INTO USERS (USERNAME, PASSWORD, FIRST_NAME, SURNAME, PHONE_NUMBER)
VALUES ('user2', 'password2', 'Jane', 'Smith', '987-654-3210');

-- Insert some roles
INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION)
VALUES ('ROLE_ADMIN', 'Administrator Role');

INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION)
VALUES ('ROLE_USER', 'User Role');

-- Associate roles with users
INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
VALUES (
           (SELECT ID FROM USERS WHERE USERNAME = 'user1'),
           (SELECT ID FROM ROLE WHERE ROLE_NAME = 'ROLE_ADMIN')
       );

INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
VALUES (
           (SELECT ID FROM USERS WHERE USERNAME = 'user2'),
           (SELECT ID FROM ROLE WHERE ROLE_NAME = 'ROLE_USER')
       );
