version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpassword
      POSTGRES_DB: dockerdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

#  app:
#    build: .
#    image: meeting-app-image
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dockerdb
#      SPRING_DATASOURCE_USERNAME: dockeruser
#      SPRING_DATASOURCE_PASSWORD: dockerpassword
#    networks:
#      - mynetwork

volumes:
  postgres-data:

networks:
  mynetwork: